<a href="https://colab.research.google.com/github/IamAtreus/00-Tensorflow/blob/PyTorch/00_pytorch_for_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###PyTorch in Deep Learning
**Prelude to UCL project with deadline on december 15**


In [1]:
import tensorflow as tf
import numpy as np
import torch as t
import torchvision as tv 
import torchaudio as ta 
import matplotlib.pyplot as plt

print(t.__version__)


1.12.1+cu113


In [2]:
!nvidia-smi


NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
## Tensors
## scaler
scalar = t.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim
scalar.item()


7

In [5]:
# vector
vector = t.tensor([7, 7]) 

vector


tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = t.tensor([[ 7, 8],
                  [9, 10]])
matrix.shape

torch.Size([2, 2])

In [9]:
TENSOR = t.tensor([[[1, 2, 3],
                    [4, 6, 9],
                    [23, 34, 76]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  6,  9],
         [23, 34, 76]]])

In [10]:
TENSOR.ndim

3

In [11]:
random_tensor = t.rand(1, 10, 10)
random_tensor

tensor([[[0.8763, 0.1691, 0.2178, 0.8251, 0.9095, 0.5902, 0.6615, 0.2344,
          0.6191, 0.3686],
         [0.8825, 0.0326, 0.1415, 0.9978, 0.1035, 0.7818, 0.3663, 0.5202,
          0.7626, 0.0117],
         [0.3641, 0.5191, 0.3808, 0.1832, 0.2035, 0.7876, 0.0661, 0.5547,
          0.8872, 0.4263],
         [0.1862, 0.0629, 0.9562, 0.2703, 0.7781, 0.2600, 0.8575, 0.3983,
          0.4092, 0.7862],
         [0.6716, 0.2824, 0.1844, 0.2662, 0.9737, 0.5598, 0.6663, 0.6981,
          0.0089, 0.0266],
         [0.4789, 0.1847, 0.1069, 0.9141, 0.9100, 0.3177, 0.8217, 0.2207,
          0.9427, 0.5508],
         [0.7523, 0.6906, 0.6216, 0.8726, 0.5301, 0.7293, 0.8916, 0.7154,
          0.4123, 0.4021],
         [0.8570, 0.2908, 0.5427, 0.5102, 0.8202, 0.8590, 0.1384, 0.9810,
          0.5446, 0.3054],
         [0.0765, 0.5522, 0.4553, 0.7415, 0.3284, 0.0488, 0.3707, 0.8517,
          0.0183, 0.3994],
         [0.0676, 0.6705, 0.2995, 0.9983, 0.8237, 0.8995, 0.2585, 0.3846,
          0.3538,

In [12]:
# image tensor
random_image_size_tensor = t.rand(size=(224, 224 ,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### tensors range

In [13]:
on_to_ten = t.arange(start=0, end=10, step=1) # instead of range
on_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# PyTorch tensors and NumPy


In [19]:
import torch as t
import numpy as np 

array = np.arange(1.0, 8.0)
torch = t.from_numpy(array) # converts to dtype float64 from numpy float32
array, torch

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [21]:
tensor = t.ones(7)
numpy_tensors = tensor.numpy()
tensor, numpy_tensors

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))