<a href="https://colab.research.google.com/github/IamAtreus/00-Tensorflow/blob/PyTorch/00_pytorch_for_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###PyTorch in Deep Learning
**Prelude to UCL project with deadline on december 15**


In [6]:
import tensorflow as tf
import numpy as np
import torch as t
import torchvision as tv 
import torchaudio as ta 
import matplotlib.pyplot as plt

print(t.__version__)


1.12.1+cu113


In [7]:
!nvidia-smi


NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [8]:
## Tensors
## scaler
scalar = t.tensor(7)
scalar


tensor(7)

In [9]:
scalar.ndim
scalar.item()


7

In [10]:
# vector
vector = t.tensor([7, 7]) 

vector


tensor([7, 7])

In [11]:
vector.ndim


1

In [12]:
vector.shape

torch.Size([2])

In [13]:
matrix = t.tensor([[ 7, 8],
                  [9, 10]])
matrix.shape

torch.Size([2, 2])

In [14]:
TENSOR = t.tensor([[[1, 2, 3],
                    [4, 6, 9],
                    [23, 34, 76]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  6,  9],
         [23, 34, 76]]])

In [15]:
TENSOR.ndim

3

In [16]:
random_tensor = t.rand(1, 10, 10)
random_tensor

tensor([[[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753,
          0.8860, 0.5832],
         [0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644,
          0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068,
          0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587,
          0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666,
          0.9811, 0.0874],
         [0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591,
          0.7653, 0.2979],
         [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057, 0.3725,
          0.7980, 0.8399],
         [0.1374, 0.2331, 0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249,
          0.4340, 0.1371],
         [0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816, 0.9998, 0.5944,
          0.6541, 0.0337],
         [0.1716, 0.3336, 0.5782, 0.0600, 0.2846, 0.2007, 0.5014, 0.3139,
          0.4654,

In [17]:
# image tensor
random_image_size_tensor = t.rand(size=(224, 224 ,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### tensors range

In [18]:
on_to_ten = t.arange(start=0, end=10, step=1) # instead of range
on_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# PyTorch tensors and NumPy


In [19]:
import torch as t
import numpy as np 

array = np.arange(1.0, 8.0)
torch = t.from_numpy(array) # converts to dtype float64 from numpy float32
array, torch

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [20]:
tensor = t.ones(7)
numpy_tensors = tensor.numpy()
tensor, numpy_tensors

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [21]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

randomseed_a = torch.rand(3,4)
randomseed_b = torch.rand(3,4)

print(randomseed_a)
print(randomseed_b)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


In [3]:
import torch
!nvidia-smi
torch.cuda.is_available()

Sat Nov 12 05:46:39 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

True

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device


'cuda'

In [5]:
torch.cuda.device_count()

1